version: '2'
services:
  web:
    build: src
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8001:8001
    restart: always
    volumes:
      - ./src:/app
      - /tmp:/report:ro
      - /tmp/ansible_tasks:/app/tasks
      # - ./sockets:/sockets

        # nginx_server:
        #   build: server 
        #   restart: always
        #   environment:
        #     - "TZ=Asia/Shanghai"
        #   ports:
        #     - 8001:80
        #   volumes:
        #     - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
        #     - ./nginx_log:/var/log/nginx
        #     - ./sockets:/sockets
