FROM nginx:1.13.1
# Make NGINX run on the foreground
# RUN echo "daemon off;" >> /etc/nginx/nginx.conf
# Remove default configuration from Nginx
# COPY localtime /etc/localtime
CMD ["nginx", "-g", "daemon off;"]
