- name: CloudEngine command test
  hosts: huawei
  connection: local
  gather_facts: no

  tasks:
    - name: "Run display version on remote devices"
      ce_command:
        commands: display version

      register: output

    - debug: msg="Hello World! {{ output.stdout }}"
    - debug: var=output
