---
- name: test route
  hosts: server
  gather_facts: false
  connection: local

  tasks:
    - name: test 
      shell: ls /tmp

      register: output




    # - name: run show commands
    #   telnet:
    #     user: cisco
    #     password: cisco
    #     login_prompt: "Username: "
    #     prompts:
    #       - "[>|#]"
    #     command:
    #       - terminal length 0
    #       - show version
    #       - enable ciscojmy
    #       - configure terminal

    - debug: msg="Hello World! {{ output.stdout }}"
    - debug: var=output
    # - debug: var=output.stdout_lines

