mysql_host: mydb.com
mysql_user: 'root'
mysql_pass: 'root'

zabbix_host: zabbix.com
zabbix_port: '8081'

# elk_host= 32.3.160.239
elk_host: elk.com
elk_port: '80'

# grafana_host= 32.3.160.239
grafana_host: grafana.com
grafana_port: '8000'

